TYPE_NUMBER: 7
TYPE_SKIP_CHANCE: 20
TYPE_STRING_LENGTH_RANGE: [6, 10]
TYPE_SUFFIXES_PREFIXES_NUMBER_RANGE: [0, 3]

PROCESS_MAX_DEPTH: 4
PROCESS_MAX_LENGTH: 50

REQUEST_END_CHANCE: 30

REQUEST_TIME_RANGES:
    NORMAL: [100, 800]
    MID: [801, 2000]
    LONG: [2001, 10000]
REQUEST_TIME_WEIGHTS:
    NORMAL: 75
    MID: 20
    LONG: 5

PROCESS_PATTERN_NUMBER: 4
PROCESSES_TO_GENERATE: 20